language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

python: 3.7

matrix:
  include:
  - os: linux
    python: 3.6
  - os: linux
    name: Integration install
    install:
    - python setup.py install
    - pip install gitutils[tests]
    script:
    - cd $HOME
    - python -m pytest $TRAVIS_BUILD_DIR/tests -r a -v
  - os: linux
    name: PEP8 MyPy Coverage
    install: pip install -e .[tests,cov,github]
    script:
    - flake8
    - mypy .
    - pytest -r a -v
#    after_success:
#    - pytest --cov
#    - coveralls

install: pip install -e .[tests]

script: pytest -r a -v
